### PR TITLE
Comprehensive Guide to Contributing to Open Source Projects

### PR DESCRIPTION
**Pull request by bitlevi**
**The reason behind this guide**
Modifying open-source projects is daunting for the majority of people. When I heard people say, "Just fork the project", I immediately felt unqualified. But I don't believe it doesn't have to be this way. There are fantastic technical writers who I am sure could help Bitcoiner.Guide with a little bit more instructions. 

**Quick overview of the PR**
This PR adds an extensive step-by-step guide on contributing to open-source projects using Bitcoiner.Guide as a case study. 

It covers everything from setting up a GitHub account and necessary tools, forking and cloning a project, to making and submitting changes via a pull request. It also includes instructions on making additional changes after creating a PR and keeping a fork updated. 

*Note: It passed the non-technical, non-tech-savy GF test for a simple article addition* 🤓

### CODE REVIEW

**Comment by BitcoinQnA** [comment]
Once again, thank you so much for this contribution. Just done a thorough review and this is absolutely fantastic. Here's some incredibly minor nits and feedback. Feel free to push back on any of them, this is your work :)

1. Link to this guide from the contribute page should be just `/fork` no need for the domain before it since it's an internal link
2. The link in the readme needs to be a full domain, including `https://` since it's linking from GitHub
3. It's common practice to capitalize the term `Open Source`  
4. Step 1 - Git is pre-installed on lots of machines. Worth mentioning that and linking [here](https://github.com/git-guides/install-git)
5. Step 3 - The numbers go 1 > 2 > 1 > 2 > 3 > 4 > 1. It's a little confusing
6. Step 4 - Possible typo in `dialog`. Should be `dialogue` _I think_, but I could be wrong
7. Step 5 - Numbering
8. Step 6 - Numbering
9. Step 6 - Maybe a brief mention about Markdown formatting with an external link?
10. Step 7 - Numbering
11. Anywhere you mention me by name, just use "QnA"
12. Don't forget to include the same sign off about yourself, including a place for people to tip you for this super detailed page.

Again, THANK YOU!

**Comment by bitlevi** [comment]
Thanks for reviewing this quickly and for the feedback and advice, QnA. 

The numbers are a real PITA; they start from one again whenever I add a picture. I found that this was a limitation of Markdown formatting, but I will dig deeper into it or find an alternative. 

Nothing to push back on; super good feedback once again 🙏

**Comment by BitcoinQnA** [comment]
Here's the solution for your listing

```
1. Some text
2. some text
3. some text

<p align="center">
<img src="/assets/img/NKYC2.png" class=responsive width="300" height="230" maxheight="300" />
</p>

{:start="4"}
4. Some more text
5. Some more text
```

**Comment by bitlevi** [comment]
Brilliant, smashing. Thanks!!

**Comment by bitlevi** [comment]
Thanks again for the feedback. I learnt about the internal link system and the numbering formatting! 
I have pushed the changes. Let me know if it looks good and if you think I missed an important step.

If I am not mistaken, there is a slight difference between *dialog* and *dialogue*.  The latter refers to two people or more discussing. Whereas the first could, for example, be a type of window in the GUI of an operating system or an input box popping up in software.

**Comment by BitcoinQnA** [comment]
Thank you for the speedy updates and the grammar lessons. Told you I was likely wrong!

I have to focus on a few other bits now, but will do a final review before merging this weekend.

Thank you again.

**Pull request merged**
