### PR TITLE
Added a few links

### PR DESCRIPTION
**Pull request by athena-alpha**
The Bisq Ubuntu install guide is live, however the Windows one won't be live until next Wednesday, so feel free to merge now (with a temporary broken link) or then :)

### CODE REVIEW

**Comment by BitcoinQnA** [comment]
Want to add yourself to `/qna/education` too?

**Comment by athena-alpha** [comment]
Yes thank you!

Just added at the top of the list under Bitcoin.org as there doesn't seem to be any specific order

**Comment by athena-alpha** [comment]
Added the new Passport Review and fixed up the links so everything is live now and ready to roll :)

**Comment by BitcoinQnA** [comment]
Thanks!

**Pull request merged**
